project:
  type: website
  render:
    - "index.qmd"
    - "docs/"
    - "!*.ipynb"
  preview:
    port: 1111
    browser: true
    watch-inputs: true
    navigate: true
  resources:
    - "docs/_static/**"

website:
  title: "Assess GTFS"
  favicon: docs/_static/favicon.ico
  navbar:
    logo: docs/_static/assess-gtfs.png
    left:
      - href: docs/getting_started/index.qmd
        text: Getting Started
      - href: docs/explanation/index.qmd
        text: Explanation
      - href: docs/how_to/index.qmd
        text: How-To
      - href: docs/tutorials/index.qmd
        text: Tutorials
      - href: docs/reference/index.qmd
        text: API Reference
    right:
      - icon: github
        menu:
          - text: Source code
            url: https://github.com/datasciencecampus/assess_gtfs
          - text: Open an issue
            url: https://github.com/datasciencecampus/assess_gtfs/issues
  page-footer:
    left: >
      These docs are built using [Quarto](https://quarto.org/), [quartodoc](https://machow.github.io/quartodoc/get-started/overview.html), and [Diátaxis](https://diataxis.fr/).
    center: >
      All content is available under the
      [Open Government Licence V3.0](https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/),
      except where otherwise stated.
    right: >
      <a href="https://datasciencecampus.ons.gov.uk/">
        <img src="https://datasciencecampus.ons.gov.uk/wp-content/uploads/sites/10/2019/05/DSC.png" alt="Data Science Campus logo" style="height:22px;">
      </a>

format:
  html:
    css: docs/_static/styles.css
    mainfont: Arial
    theme:
      - flatly
      - docs/_static/custom.scss
    lang: en-GB

metadata-files:
  - docs/_sidebar.yml

quartodoc:
  title: API reference
  package: assess-gtfs
  dir: docs/reference
  sidebar: docs/_sidebar.yml
  sections:
    - title: "`gtfs`"
      desc: >
        Modules for working with GTFS public transit schedule files.
      package: assess_gtfs
      contents:
        - calendar
        - cleaners
        - gtfs_utils
        - multi_validation
        - routes
        - validation
        - validators
    - title: "`utils`"
      desc: >
        Modules to handle common package utility functions.
      package: assess_gtfs.utils
      contents:
        - defence
        - io

jupyter: python3
