# Fixing OS version to avoid breaking OS changes during development stage.
# Will open up OS versions before release.

name: "Render docs"

on:
  push:
    branches: [ "dev", "main" ]

env:
  PYTHON_VERSION: "3.9"

jobs:
  build:
    name: Quarto Render
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11.0.21'
    - name: Check Java Install
      run: |
        java --version
    - name: Install linux depencies with apt
      run: |
        sudo apt update
        sudo apt install -y libgeos-dev
        sudo apt-get install osmosis
      shell: sh
    - name: Build API reference pages
      run: |
        python -m quartodoc build
    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
    - name: Render and Publish
      uses: quarto-dev/quarto-actions/publish@v2
      with:
        target: gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
