# Fixing OS version to avoid breaking OS changes during development stage.
# Will open up OS versions before release.

name: "Render docs"
on:
  push:
    branches: [ "dev", "main" ]
env:
  PYTHON_VERSION: "3.11"
jobs:
  build:
    name: Quarto Render
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # sha for 4.1.7
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d  # sha for 5.1.0
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install '.[docs]'
    - name: Install linux depencies with apt
      run: |
        sudo apt update
        sudo apt install -y libgeos-dev
      shell: sh
    - name: Build API reference pages
      run: |
        python -m quartodoc build
    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@c1b50d36cf3c22b3dc7e530bd1b36634e824e545 # sha for v2.1.4
    - name: Render and Publish
      uses: quarto-dev/quarto-actions/publish@c1b50d36cf3c22b3dc7e530bd1b36634e824e545 # sha for v2.1.4
      with:
        target: gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
